# Generated by Django 3.2.12 on 2022-02-07 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Academician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("last_name", models.CharField(max_length=250)),
                ("first_name", models.CharField(max_length=255)),
                ("matricule", models.CharField(max_length=250)),
                ("photo", models.FileField(upload_to="image_academician")),
            ],
            options={
                "verbose_name": "Academicien",
                "verbose_name_plural": "Academiciens",
            },
        ),
        migrations.CreateModel(
            name="Caisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("motif", models.CharField(max_length=50)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paiement", models.DateField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "academician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caisse_academicien",
                        to="api.academician",
                        verbose_name="academicien_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caisse",
            },
        ),
    ]
