# Generated by Django 3.2.12 on 2022-02-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_academician_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academician',
            old_name='matricule',
            new_name='registration_number',
        ),
    ]
