# Generated by Django 3.2.12 on 2022-02-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_matricule_academician_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caisse',
            old_name='montant',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='caisse',
            old_name='date_paiement',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='caisse',
            old_name='motif',
            new_name='reason',
        ),
    ]
